version: '3.6'
services:
  postgres:
    image: postgres:14.8-alpine3.18
    container_name: "postgres01"
    command:
      - "postgres"
      - "-c"
      - "max_connections=200"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=4GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
    environment:
      POSTGRES_DB: "bingo"
      POSTGRES_USER: "bingo"
      POSTGRES_PASSWORD: "Y&Ywhyyyy"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - bingo
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bingo -d bingo"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G

networks:
  bingo:
    name: bingo
    driver: bridge
    ipam:
      config:
        - subnet: 10.3.27.0/24
          gateway: 10.3.27.1
