version: '3.6'
services:
  nginx:
    image: 'nginxinc/nginx-unprivileged:1.25-alpine'
    container_name: "nginx-blns"
    restart: always
    ports:
      - '443:8443'
      - '80:8080'
    networks:
      - nginx
    volumes:
      - './config/nginx.conf:/etc/nginx/nginx.conf'
      - './config/conf.d:/etc/nginx/conf.d'
      - './config/ssl:/etc/nginx/ssl'
      - './logs:/var/log/nginx'
    shm_size: '256m'

  nginx-exporter:
    image: 'nginx/nginx-prometheus-exporter:0.10.0'
    container_name: "nginx-exporter"
    command:
      - -nginx.scrape-uri
      - http://nginx-blns:8080/basic_status
    restart: always
    ports:
      - '9113:9113'
    networks:
      - nginx

networks:
  nginx:
    name: nginx
    driver: bridge
    ipam:
      config:
        - subnet: 10.3.27.0/24
          gateway: 10.3.27.1
