- name: Login to registry
  docker_login:
    registry: "{{ REGISTRY_URL }}"
    username: "{{ REGISTRY_USER }}"
    password: "{{ REGISTRY_PWD }}"
    reauthorize: yes
  when: "inventory_hostname in groups.get('nodes', [])"

- name: Include a bingo
  import_tasks: bingo.yaml

- name: Log out from registry
  docker_login:
    registry: "{{ REGISTRY_URL }}"
    state: absent
  when: "inventory_hostname in groups.get('nodes', [])"


